In [2]:
import numpy as np

In [3]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[:5] =100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr=arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_2d= np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[1][2]

30

In [19]:
arr_2d[1,2]

30

In [20]:
arr_2d[0]

array([ 5, 10, 15])

In [21]:
arr_2d[0,:]

array([ 5, 10, 15])

In [22]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [23]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [24]:
arr_2d[1:3, 0:2]

array([[20, 25],
       [35, 40]])

In [25]:
arr = np.arange(1,11)

In [26]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [27]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [29]:
arr[arr<3]

array([1, 2])