In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
arr=np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_mat=[[1,2,3], [4,5,6], [7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [23]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(5)

array([0.92063721, 0.23314967, 0.32465429, 0.486675  , 0.17045061])

In [27]:
np.random.rand(5,5)

array([[0.05722579, 0.3906993 , 0.45890403, 0.97646567, 0.74359052],
       [0.08298015, 0.83051388, 0.41588722, 0.83502627, 0.7200052 ],
       [0.90073891, 0.39219682, 0.47849773, 0.69853976, 0.81719539],
       [0.66274728, 0.58304163, 0.10715471, 0.06815029, 0.86855662],
       [0.69704388, 0.99640883, 0.3387409 , 0.38866115, 0.04544024]])

In [28]:
np.random.randn(2)

array([0.12302329, 0.02183153])

In [29]:
np.random.randn(4,4)

array([[ 0.11455361, -0.0915192 , -0.43959369, -1.85424251],
       [ 0.4577636 , -0.47185339, -0.93049174,  0.79765845],
       [ 0.52950923,  0.60021188,  1.67037532, -0.34068416],
       [ 0.56068748, -0.48214013, -0.26723299,  1.01178784]])

In [34]:
np.random.randint(1,100,10)

array([55, 44, 97, 72, 29, 90,  2,  1, 62, 39])

In [40]:
arr= np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr=np.random.randint(0,50,10)
ranarr

array([ 3, 14, 12, 39, 20, 10, 43,  0, 28, 47])

In [42]:
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr.max()

47

In [46]:
ranarr.min()

0

In [47]:
ranarr.argmax()

9

In [49]:
ranarr.argmin()

7

In [50]:
arr.shape

(25,)

In [51]:
arr.reshape(5,5).shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')